### ISSUE TITLE
Configuration Values like true or false or functions outside of a callback tag are not working

### ISSUE THREAD

**Issue by JenHa** [YolfTypo3/SavCharts#1]
Hi, 
I'm using your Extension with TYPO3 9.5. So far it works quite well, but I found some issues: 

In the options of the charts in the xml-Template: If you want to use values like true, false or a function outside of a callback it is set into ", which unfortunatly breaks the functionality in charts.js (the option is ignored). My example is responsive: true or maintainAspectRatio: false. Maybe you could add a possibility to set these values in xml-comments like in the callback tag? This would be great. 

Also I found the problem, that only one callback is processed, but I found the fix for this and will upload it soon as a pull request. 

But help with the first problem would be great! 

Thanks and greetings

**Comment by JenHa** [comment]
Addition: 
Another approach for a solution would be to include the options over a php/javascript or maybe a yaml file, so the values aren't automatically put in strings. 
I'll try this options during this or next week, when I find some time and give feedback to you. 

Still: If you find a more elegant solution I'll be thankfull for a hint

**Comment by YolfTypo3** [comment]
Thank you for you rmessage.
Boolean values and multiple callbacks can now be used.
I have to think about the use of functions outside callbacks.

**Comment by YolfTypo3** [comment]
Please see the last item if How to? section in the documentation. It explains how to associate a Javascript function name to an event. The Javascript function must be loaded separately.

**Comment by JenHa** [comment]
Now everythings working fine! Thanks a lot!
