### ISSUE TITLE
error message in logfile

### ISSUE THREAD

**Issue by averlon** [YolfTypo3/SavCharts#5]
Hi,
what does this tell me?
`Fri, 10 Feb 2023 11:34:29 +0100 [WARNING] request="ffc7cd62d7b75" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: Undefined array key "idTagName" in /var/www/html/averlon.de/av_homep/public/typo3conf/ext/sav_charts/Classes/XmlParser/XmlParser.php line 847`

I assume it is the attached file bringing the error.
[gw_chart1.txt](https://github.com/YolfTypo3/SavCharts/files/10706426/gw_chart1.txt)

**Comment by YolfTypo3** [comment]
Hi, 
Please give more details. Using your file in the Templates section works fine.
`<template id="1">
      fileadmin/gw_chart1.txt
</template>`

**Comment by averlon** [comment]
Hi Laurent,
I don't have more details. This is the message I saw in the T3 logfile. And this is the file which probably caused this message.

What more details are you looking for - probably I can try to provide them.

**Comment by averlon** [comment]
Hi Laurent,
I use:
`<template id="grundwasserpegel">
fileadmin/av_images/gw_chart1.xml
</template>
`


But I guess it is equal to use a text ID or a numeric ID

**Comment by averlon** [comment]
Hi Laurent,
I have setup a complete new VM with a T3 Development System. My intention is to start my own Extension.
SAV_Chart brings some error messages on the FE Page. See attached file (.html).
Can you find out what the reason for these messages could be?

[TYPO3 Exception.txt](https://github.com/YolfTypo3/SavCharts/files/10821563/TYPO3.Exception.txt)

**Comment by YolfTypo3** [comment]
Hi,
I guess your configuration generates warnings on undefined array keys (it occurs when E_NOTICE is set in my TYPO3 configuration). I have uploaded new files. Please confirm that it solves this issue.

**Comment by averlon** [comment]
Hi Laurent,
I confirm, no error messages anymore and chart is shown in FE as expected.

Thanks for help.

**Comment by averlon** [comment]
Hi Laurent,
I had to reinstall my test environment with T3 11.5.24 again.
After installing SAV_Charts from Compser (11.5.0) it looks like I get the same error again.
Had you been able to update the files according to your changes on packagist.org or do I have to pick it from github again?
